include:
  - project: airbornemint/gitlab-autodocker
    file: "gitlab-autodocker.yml"

stages:
  - autodocker
  - build
  - pages
  - check

variables:
  R_BUILD_DIR: "build"
  R_PACKAGE_CACHE: ".cache/r"
  AUTODOCKER_CONTEXT_NAME: build
  
.r:
  extends: .use-autodocker
  before_script:
    - mkdir -p /usr/local/lib/R/etc
    - echo "options(Ncpus = $(nproc --all))" >> "/usr/local/lib/R/etc/Rprofile.site"
    - mkdir -p "${R_PACKAGE_CACHE}"
    - echo "R_LIBS_USER=${R_PACKAGE_CACHE}" >> .Renviron
    - echo "R_PACKAGE_CACHE=${R_PACKAGE_CACHE}" >> .Renviron
    - Rscript -e "devtools::install_deps(repos=c(getOption('repos'), INLA='https://inla.r-inla-download.org/R/stable'))"
    - Rscript -e "devtools::install_dev_deps(repos=c(getOption('repos'), INLA='https://inla.r-inla-download.org/R/stable'))"
  
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "${R_PACKAGE_CACHE}"
  
build-release:
  extends: .r
  tags:
    - docker-cpu:4
  stage: build
  script:
    - mkdir -p "${R_BUILD_DIR}"
    - Rscript -e "devtools::build(pkg = '.', path = '${R_BUILD_DIR}', vignettes = TRUE, binary = FALSE)"
  artifacts:
    paths:
      - "${R_BUILD_DIR}/InterventionEvaluatR*.tar.gz"
    when: always

check-release:
  extends: .r
  tags:
    - docker-mem:4 # True story: R cmd check fails if you use more than 2 CPUs
  stage: check
  script:
    - Rscript -e "devtools::check_built(path = paste0('${R_BUILD_DIR}/', list.files('${R_BUILD_DIR}', pattern='InterventionEvaluatR.*t.*gz')[1]))"
    
pages:
  extends: .use-autodocker
  stage: pages
  variables:
    PAGES_BUILD_DIR: "public"
  script:
    - mkdir -p "${PAGES_BUILD_DIR}"
    - tar -C "${R_BUILD_DIR}" -xvzf "${R_BUILD_DIR}"/InterventionEvaluatR*.tar.gz
    - cp "${R_BUILD_DIR}"/InterventionEvaluatR/inst/doc/*.html "${PAGES_BUILD_DIR}"
    - pandoc --from markdown --to html --standalone --output "${PAGES_BUILD_DIR}/index.html" README.md
  artifacts:
    paths:
      - public
  environment:
    name: "weinbergerlab.gitlab.io"
    url: "http://weinbergerlab.gitlab.io/InterventionEvaluatR"
  dependencies:
    - build-release
  only:
    - master
    - vignette-webpages

# Set up docker image for the rest of the build, keyed off commit ID
autodocker:
  extends: .autodocker
  tags: 
    - dind-mem:2
